# Generated by Django 5.2.3 on 2025-08-30 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="is_read",
            new_name="read",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="crime",
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="No Title", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
