# Generated by Django 5.2.3 on 2025-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
