# Generated by Django 5.2.3 on 2025-08-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrimeIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crime_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("date_time", models.DateTimeField()),
                ("severity", models.CharField(max_length=50)),
                ("precautions", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="reported", max_length=50)),
            ],
        ),
    ]
