# Generated by Django 5.2.3 on 2025-08-30 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime_data", "0001_initial"),
        ("notifications", "0002_rename_is_read_notification_read_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crime_type",
                    models.CharField(
                        choices=[
                            ("THEFT", "Theft"),
                            ("ASSAULT", "Assault"),
                            ("ROBBERY", "Robbery"),
                            ("FRAUD", "Fraud"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descriptions", models.TextField()),
                (
                    "location_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "location_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("processed_by_ai", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CrimeIncident",
        ),
    ]
