# Generated by Django 5.2.3 on 2025-09-03 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime_data", "0002_crimerecord_delete_crimeincident"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrimeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "crime_reports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.TextField(blank=True, null=True)),
                ("new_reports", models.IntegerField(default=0)),
                ("status", models.TextField(default="success")),
            ],
            options={
                "db_table": "pipeline_log",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="CrimeRecord",
        ),
    ]
